# report/templates.py
"""
Templates for report generation.
"""

EXCEL_TEMPLATE_HEADER = [
    "Filename", 
    "Extension", 
    "Size (KB)", 
    "Modified Date", 
    "Is Excel", 
    "Has VBA", 
    "Has PivotTable", 
    "Row Count", 
    "Column Count",
    "Sheet Count",
    "Delimiter",
    "Encoding"
]

# HTML report template
HTML_REPORT_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Excel and CSV File Analysis Report</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
            margin: 20px;
            line-height: 1.6;
            color: #333;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            color: #2c3e50;
            border-bottom: 2px solid #eaecef;
            padding-bottom: 10px;
        }
        h2 {
            color: #3498db;
            margin-top: 30px;
        }
        .container {
            background-color: #fff;
            border-radius: 5px;
            box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            padding: 20px;
            margin-bottom: 20px;
        }
        .summary {
            margin-bottom: 30px;
            background-color: #f8f9fa;
            padding: 15px;
            border-radius: 5px;
            border-left: 5px solid #3498db;
        }
        .meta-info {
            color: #7f8c8d;
            font-size: 0.9em;
            margin-bottom: 20px;
        }
        table {
            border-collapse: collapse;
            width: 100%;
            margin-bottom: 20px;
            font-size: 0.9em;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
            position: sticky;
            top: 0;
        }
        tr:nth-child(even) {
            background-color: #f9f9f9;
        }
        tr:hover {
            background-color: #f5f5f5;
        }
        .data-table-container {
            max-height: 700px;
            overflow-y: auto;
            margin-top: 20px;
        }
        .summary-table {
            width: auto;
            min-width: 300px;
        }
        .summary-table th {
            background-color: #3498db;
            color: white;
        }
        .error {
            color: #e74c3c;
        }
        .footer {
            margin-top: 30px;
            padding-top: 10px;
            border-top: 1px solid #eaecef;
            color: #7f8c8d;
            font-size: 0.8em;
            text-align: center;
        }
    </style>
</head>
<body>
    <h1>Excel and CSV File Analysis Report</h1>
    
    <div class="meta-info">
        <p>Generated on: {date}</p>
    </div>
    
    {summary}
    
    <div class="container">
        <h2>File Analysis Results</h2>
        <div class="data-table-container">
            <table class="data-table">
                <thead>
                    <tr>
                        {headers}
                    </tr>
                </thead>
                <tbody>
                    {rows}
                </tbody>
            </table>
        </div>
    </div>
    
    <div class="footer">
        <p>Generated by Excel and CSV Inspector Tool</p>
    </div>
</body>
</html>
"""

# Basic text report template
TEXT_REPORT_TEMPLATE = """
Excel and CSV File Analysis Report
=================================
Generated on: {date}

Summary
-------
Total files analyzed: {total_files}
Excel files: {excel_files}
CSV files: {csv_files}
Files with VBA: {vba_files}
Files with PivotTables: {pivot_files}

Detailed Results
---------------
{results}

"""

# JSON report schema template
JSON_SCHEMA = {
    "metadata": {
        "generated_at": "",  # ISO timestamp
        "file_count": 0,
        "excel_count": 0,
        "csv_count": 0,
        "vba_count": 0,
        "pivot_count": 0
    },
    "results": []  # List of file analysis results
}